import { fetchActions } from "@root/redux/utils";
import { fetchCodeMe, fetchDiscussionForum, fetchDiscussionForums, fetchDobAndAddress } from "@root/service/code/member/general";
import { fetchInstructorCourseReviews, fetchInstructorDestroyCourse, fetchInstructorDestroyLesson, fetchInstructorDestroySection, fetchInstructorEarnings, fetchInstructorPayout, fetchInstructorQuestions, fetchInstructorStoreAnswer, fetchInstructorStoreCourse, fetchInstructorStoreLesson, fetchInstructorStoreSection, fetchInstructorUpdateAnswer, fetchInstructorUpdateCourse, fetchInstructorUpdateLesson, fetchInstructorUpdateSection, fetchinstructorSections, fetchInstructorStudies, fetchinstructorLessons } from "@root/service/code/member/instructor";
import { fetchStudentAnswers, fetchStudentCertificate, fetchStudentCertificates, fetchStudentCourseProgress, fetchStudentCourses, fetchStudentDestroyReview, fetchStudentDestroyStash, fetchStudentDestroyTransaction, fetchStudentLessons, fetchStudentQuestion, fetchStudentReviews, fetchStudentSections, fetchStudentStashes, fetchStudentStoreReview, fetchStudentStoreStash, fetchStudentStoreTransaction, fetchStudentStoreTransactionFree, fetchStudentTransactions, fetchStudentUpdateCompletedLectures, fetchStudentUpdateReview } from "@root/service/code/member/student";

export const discussionForumsActions = fetchActions('DISCUSSION_FORUMS', fetchDiscussionForums)
export const discussionForumActions = fetchActions('DISCUSSION_FORUM', fetchDiscussionForum)
export const codeMeActions = fetchActions('CODE_ME', fetchCodeMe)
export const dobAndAddressActions = fetchActions('DOB_ADDRESS', fetchDobAndAddress)

export const instructorQuestionsActions = fetchActions('INSTRUCTOR_QUESTIONS', fetchInstructorQuestions)
export const instructorStoreAnswerActions = fetchActions('INSTRUCTOR_STORE_ANSWER', fetchInstructorStoreAnswer)
export const instructorUpdateAnswerActions = fetchActions('INSTRUCTOR_UPDATE_ANSWER', fetchInstructorUpdateAnswer)
export const instructorCourseReviewsActions = fetchActions('INSTRUCTOR_COURSE_REVIEWS', fetchInstructorCourseReviews)
export const instructorEarningsActions = fetchActions('INSTRUCTOR_EARNINGS', fetchInstructorEarnings)
export const instructorPayoutActions = fetchActions('INSTRUCTOR_PAYOUT', fetchInstructorPayout)
export const instructorStudiesActions = fetchActions('INSTRUCTOR_STUDIES', fetchInstructorStudies)
export const instructorStoreCourseActions = fetchActions('INSTRUCTOR_STORE_COURSE', fetchInstructorStoreCourse)
export const instructorUpdateCourseActions = fetchActions('INSTRUCTOR_UPDATE_COURSE', fetchInstructorUpdateCourse)
export const instructorDestroyCourseActions = fetchActions('INSTRUCTOR_DESTROY_COURSE', fetchInstructorDestroyCourse)
export const instructorSectionsActions = fetchActions('INSTRUCTOR_SECTIONS', fetchinstructorSections)
export const instructorStoreSectionActions = fetchActions('INSTRUCTOR_STORE_SECTION', fetchInstructorStoreSection)
export const instructorUpdateSectionActions = fetchActions('INSTRUCTOR_UPDATE_SECTION', fetchInstructorUpdateSection)
export const instructorDestroySectionActions = fetchActions('INSTRUCTOR_DESTROY_SECTION', fetchInstructorDestroySection)
export const instructorLessonsActions = fetchActions('INSTRUCTOR_LESSONS', fetchinstructorLessons)
export const instructorStoreLessonActions = fetchActions('INSTRUCTOR_STORE_LESSON', fetchInstructorStoreLesson)
export const instructorUpdateLessonActions = fetchActions('INSTRUCTOR_UPDATE_LESSON', fetchInstructorUpdateLesson)
export const instructorDestroyLessonActions = fetchActions('INSTRUCTOR_DESTROY_LESSON', fetchInstructorDestroyLesson)

export const studentCertificatesActions = fetchActions('STUDENT_CERTIFICATES', fetchStudentCertificates)
export const studentCertificateActions = fetchActions('STUDENT_CERTIFICATE', fetchStudentCertificate)
export const studentReviewsActions = fetchActions('STUDENT_REVIEWS', fetchStudentReviews)
export const studentStoreReviewActions = fetchActions('STUDENT_STORE_REVIEW', fetchStudentStoreReview)
export const studentUpdateReviewActions = fetchActions('STUDENT_UPDATE_REVIEW', fetchStudentUpdateReview)
export const studentDestroyReviewActions = fetchActions('STUDENT_DESTROY_REVIEW', fetchStudentDestroyReview)
export const studentAnswersActions = fetchActions('STUDENT_ANSWERS', fetchStudentAnswers)
export const studentQuestionActions = fetchActions('STUDENT_QUESTION', fetchStudentQuestion)
export const studentStashesActions = fetchActions('STUDENT_STASHES', fetchStudentStashes)
export const studentStoreStashActions = fetchActions('STUDENT_STORE_STASH', fetchStudentStoreStash)
export const studentDestroyStashActions = fetchActions('STUDENT_DESTROY_STASH', fetchStudentDestroyStash)
export const studentCoursesActions = fetchActions('STUDENT_COURSES', fetchStudentCourses)
export const studentSectionsActions = fetchActions('STUDENT_SECTIONS', fetchStudentSections)
export const studentLessonsActions = fetchActions('STUDENT_LESSONS', fetchStudentLessons)
export const studentCourseProgressActions = fetchActions('STUDENT_COURSE_PROGRESS', fetchStudentCourseProgress)
export const studentUpdateCompletedLecturesActions = fetchActions('STUDENT_UPDATE_COMPLETED_LECTURES', fetchStudentUpdateCompletedLectures)
export const studentTransactionsActions = fetchActions('STUDENT_TRANSACTIONS', fetchStudentTransactions)
export const studentStoreTransactionActions = fetchActions('STUDENT_STORE_TRANSACTION', fetchStudentStoreTransaction)
export const studentStoreTransactionFreeActions = fetchActions('STUDENT_STORE_TRANSACTION_FREE', fetchStudentStoreTransactionFree)
export const studentDestroyTransactionActions = fetchActions('STUDENT_DESTROY_TRANSACTION', fetchStudentDestroyTransaction)