import { combineReducers } from "redux";

import { searchCourseReducer, verifyCertificateReducer } from "./reducers/guest";

import {
    discussionForumsReducer,
    discussionForumReducer,
    codeMeReducer,
    dobAndAddressReducer,

    instructorQuestionsReducer,
    instructorStoreAnswerReducer,
    instructorUpdateAnswerReducer,
    instructorCourseReviewsReducer,
    instructorEarningsReducer,
    instructorPayoutReducer,
    instructorStudiesReducer,
    instructorStoreCourseReducer,
    instructorUpdateCourseReducer,
    instructorDestroyCourseReducer,
    instructorSectionsReducer,
    instructorStoreSectionReducer,
    instructorUpdateSectionReducer,
    instructorDestroySectionReducer,
    instructorLessonsReducer,
    instructorStoreLessonReducer,
    instructorUpdateLessonReducer,
    instructorDestroyLessonReducer,

    studentCertificatesReducer,
    studentCertificateReducer,
    studentReviewsReducer,
    studentStoreReviewReducer,
    studentUpdateReviewReducer,
    studentDestroyReviewReducer,
    studentAnswersReducer,
    studentQuestionReducer,
    studentStashesReducer,
    studentStoreStashReducer,
    studentDestroyStashReducer,
    studentCoursesReducer,
    studentSectionsReducer,
    studentLessonsReducer,
    studentCourseProgressReducer,
    studentUpdateCompletedLecturesReducer,
    studentTransactionsReducer,
    studentStoreTransactionReducer,
    studentStoreTransactionFreeReducer,
    studentDestroyTransactionReducer,
} from './reducers/member'

export const CodeReducers = combineReducers({
    // guest
    searchCourseResult: searchCourseReducer,
    verifyCertificateResult: verifyCertificateReducer,

    // member
    discussionForumsResult: discussionForumsReducer,
    discussionForumResult: discussionForumReducer,
    codeMeResult: codeMeReducer,
    dobAndAddressResult: dobAndAddressReducer,

    instructorQuestionsResult: instructorQuestionsReducer,
    instructorStoreAnswerResult: instructorStoreAnswerReducer,
    instructorUpdateAnswerResult: instructorUpdateAnswerReducer,
    instructorCourseReviewsResult: instructorCourseReviewsReducer,
    instructorEarningsResult: instructorEarningsReducer,
    instructorPayoutResult: instructorPayoutReducer,
    instructorStudiesResult: instructorStudiesReducer,
    instructorStoreCourseResult: instructorStoreCourseReducer,
    instructorUpdateCourseResult: instructorUpdateCourseReducer,
    instructorDestroyCourseResult: instructorDestroyCourseReducer,
    instructorSectionsResult: instructorSectionsReducer,
    instructorStoreSectionResult: instructorStoreSectionReducer,
    instructorUpdateSectionResult: instructorUpdateSectionReducer,
    instructorDestroySectionResult: instructorDestroySectionReducer,
    instructorLessonsResult: instructorLessonsReducer,
    instructorStoreLessonResult: instructorStoreLessonReducer,
    instructorUpdateLessonResult: instructorUpdateLessonReducer,
    instructorDestroyLessonResult: instructorDestroyLessonReducer,

    studentCertificatesResult: studentCertificatesReducer,
    studentCertificateResult: studentCertificateReducer,
    studentReviewsResult: studentReviewsReducer,
    studentStoreReviewResult: studentStoreReviewReducer,
    studentUpdateReviewResult: studentUpdateReviewReducer,
    studentDestroyReviewResult: studentDestroyReviewReducer,
    studentAnswersResult: studentAnswersReducer,
    studentQuestionResult: studentQuestionReducer,
    studentStashesResult: studentStashesReducer,
    studentStoreStashResult: studentStoreStashReducer,
    studentDestroyStashResult: studentDestroyStashReducer,
    studentCoursesResult: studentCoursesReducer,
    studentSectionsResult: studentSectionsReducer,
    studentLessonsResult: studentLessonsReducer,
    studentCourseProgressResult: studentCourseProgressReducer,
    studentUpdateCompletedLecturesResult: studentUpdateCompletedLecturesReducer,
    studentTransactionsResult: studentTransactionsReducer,
    studentStoreTransactionResult: studentStoreTransactionReducer,
    studentStoreTransactionFreeResult: studentStoreTransactionFreeReducer,
    studentDestroyTransactionResult: studentDestroyTransactionReducer,
})